apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::961747818607:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::961747818607:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OIW31XBDLSZN
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-22T18:10:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1438"
  uid: 607ecb48-9255-4178-b4d4-af1cf8a6dab2
